#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Specify mount name"
    exit -1
fi
tab=$(printf '\t')

found=false
hostname=""
user=""
remotepath=""
localmount=""

while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ -n "$line" && "$line" != "$tab"* ]]; then
    	if [[ "$line" == "$1:" ]]; then
    		read -r line
    		arrIN=(${line//;/ })
    		declare $arrIN="${arrIN[1]}"
    		read -r line
    		arrIN=(${line//;/ })
    		declare $arrIN="${arrIN[1]}"
    		read -r line
    		arrIN=(${line//;/ })
    		declare $arrIN="${arrIN[1]}"
    		read -r line
    		arrIN=(${line//;/ })
    		declare $arrIN="${arrIN[1]}"
    		found=true
    	fi
    fi
done < "$HOME/.mnt_script/mnt_points"

eval localmount=$localmount

if [ "$found" = true ]; then
	sudo sshfs -o allow_other,reconnect,defer_permissions,noappledouble,defer_permissions,IdentityFile=~/.ssh/id_rsa $user@$hostname:$remotepath "$localmount"
fi
